---
- name: Install Docker
  hosts: localhost
  become: yes
  become_method: sudo
  vars:
       user_account: ubuntu
       mount_point: /var/lib/docker
  tasks:
      # have to use cURL because of https://github.com/ansible/ansible/issues/12161
    - name: Install cURL
      apt: name=curl state=latest update_cache=true cache_valid_time=600
    - name: Download Docker Installation Script
      command: /usr/bin/curl --location --output /root/install-docker https://get.docker.com/ creates=/root/install-docker
    - name: Set Permission Bits On The Docker Installation Script
      file: path=/root/install-docker owner=root group=root mode=0500
    - name: Execute Docker Installation Script
      shell: /root/install-docker creates=/usr/bin/docker
    - name: Set Memory and Swap Accounting
      lineinfile: dest=/etc/default/grub regexp='^GRUB_CMDLINE_LINUX=""' line='GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"'
    - name: Rebuild Grub
      command: /usr/sbin/update-grub
    - name: Make some adjustments to the Docker configuration
      lineinfile: dest=/etc/default/docker line='DOCKER_OPTS="-H unix:///var/run/docker.sock --storage-driver=aufs --log-driver=syslog --graph={{ mount_point }}"'
    - name: Add account to the docker group 
      user: name={{ user_account }} groups=docker
    - name: Restart Docker
      service: name=docker state=restarted
    - name: Test Docker
      command: docker run hello-world
